spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Projeto-I-Web-II
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    fetch-register: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    url: .

security:
  jwt:
    expiracao: 30
    chave-assinatura: T0xIQSBTTyBWT0NFIFFVRSBjb2lzYSBtYWlzIGxlZ2FsIHNlZ3VyYXIgZXNzYSBiYXJyYSBxdWUggiBnb3N0YWRlIHZjISEhISE=
